### ISSUE TITLE
Replace Tabs with Spaces

### ISSUE THREAD

**Issue by mattietea** [danjkim21/portfolio-daniel-kim#15]
Who hurt you?

1. Update Prettier config

```diff
{
  "tabWidth": 2,
  "printWidth": 80,
  "endOfLine": "auto",
  "arrowParens": "always",
  "trailingComma": "es5",
  "semi": true,
-  "useTabs": false,
+  "useTabs": true,
   "singleQuote": true,
  "bracketSpacing": true
}

```

2. Format files

```bash
npm run format:fix
```

3. Squash all your commits into one so nobody knows you ever used tabs

```bash
git reset --soft $(git rev-list --max-parents=0 HEAD) && git commit --amend -m "init"
```

**Comment by danjkim21** [comment]
![image](https://github.com/user-attachments/assets/6dd03b40-b198-4ead-8a53-cd81b176720d)

**Comment by danjkim21** [comment]
![image](https://github.com/user-attachments/assets/6dd03b40-b198-4ead-8a53-cd81b176720d)

**Comment by danjkim21** [comment]
![image](https://github.com/user-attachments/assets/6dd03b40-b198-4ead-8a53-cd81b176720d)
